device: cuda:0

dataset:
  name: SomicDataset
  path: /app/github/data/H_body_normal

augs:
  train:
  - name: HorizontalFlip
    args:
      p: 0.5
  - name: RandomCrop
    args:
      height: 128
      width: 128
      always_apply: True
      p: 1
  - name: Normalize
    args:
      always_apply: True
      p: 1
  test:
  - name: Normalize
    args:
      always_apply: True
      p: 1

optim:
  name: Adam
  lr: 0.0002
  weight_decay: 0.00001

criterion:
  name: MSELoss

train:
  epochs: 1000
  batch_size: 1
  teacher_pth_path: /dgx/inoue/teacher.pth
  student_pth_path: /dgx/inoue/student.pth

inference:
  img:
    path: /app/github/data/H_body_anomaly/63_2020_0610_131357[5].bmp
  mask:
    path: /app/github/data/H_body_anomaly/63_2020_0610_131357[5].bmp
  savefig:
    path: /app/github/63_2020_0610_131357[5]_output.png
