device: cuda:0
&patch_size: 128

dataset:
  name: SomicDataset
  train:
    img: /app/github/data/bottle/train/good
    mask:
  test:
    normal:
      img: /app/github/data/bottle/test/good
      mask:
    anomaly:
      img: /app/github/data/bottle/test/broken_small
      mask: /app/github/data/bottle/ground_truth/broken_small

augs:
  train:
  - name: HorizontalFlip
    args:
      p: 0.5
  - name: RandomCrop
    args:
      height: *patch_size
      width: *patch_size
      always_apply: True
      p: 1
  - name: Normalize
    args:
      always_apply: True
      p: 1
  test:
  - name: Normalize
    args:
      always_apply: True
      p: 1

optim:
  name: Adam
  lr: 0.0002
  weight_decay: 0.00001

criterion:
  name: MSELoss

train:
  epochs: 1000
  batch_size: 1
  teacher_pth_path: /dgx/inoue/teacher.pth
  student_pth_path: /dgx/inoue/student.pth

inference:
  savefig:
    normal: /app/github/STAD/anomaly_maps/normal
    anomaly: /app/github/STAD/anomaly_maps/anomaly