device: cuda:0
patch_size: 128

dataset:
  name: MVTecDataset
  base: /dgx/data/MVTec
  train: ${dataset.base}/train
  val: ${dataset.base}/train
  test:
    defect: broken_small
    anomaly: ${dataset.base}/test/${dataset.test.defect}
    normal: ${dataset.base}/test/normal

train:
  augs: /dgx/github/STAD/stad/yamls/train_augmentations.yaml
  pretrained:
    school:
    student:
    teacher:
  pruning_rate: 0.05
  epochs: 100
  batch_size: 16
  optim:
    name: Adam
    lr: 0.0002
    weight_decay: 0.00001
  criterion:
    name: MSELoss

val:
  augs: /dgx/github/STAD/stad/yamls/test_augmentations.yaml
  data_num: 8

test:
  augs: /dgx/github/STAD/stad/yamls/test_augmentations.yaml
  batch_size: 32
  unfold_stride: 64
