device: 'cuda:3'
patch_size: 128
in_channels: 3

dataset:
  name: 'MVTecDataset'
  train: 
    normal: '/dgx/data/MVTec/train'
  val:
    normal: '/dgx/data/MVTec/val'
  test:
    normal: '/dgx/data/MVTec/test/normal'
    anomaly: '/dgx/data/MVTec/test/contamination'

augs:
  train:
  - name: 'ProbabilisticCrop'
    args:
      height: 128
      width: 128
      always_apply: True
      p: 1
  - name: 'Normalize'
    args:
      always_apply: True
      p: 1
  test:
  - name: 'Normalize'
    args:
      always_apply: True
      p: 1

optim:
  name: 'Adam'
  lr: 0.0002
  weight_decay: 0.00001

criterion:
  name: 'MSELoss'

pretrained_models:
  school: '/dgx/github/STAD/stad/outputs/2020-07-14/00-47-15/school.pth'
  student:
  teacher:

train:
  epochs: 10
  mini_epochs: 2
  batch_size: 1

test:
  batch_size: 64
  unfold_stride: 4