device: 'cuda:0'
patch_size: 128

dataset:
  name: 'SomicDataset'
  train:
    normal: '/dgx/shared/momo/inoue/somic/dataset/2020-06-18_H_tobu_for_unsupervise/train/normal/11'
  val:
    normal: '/dgx/shared/momo/inoue/somic/dataset/2020-06-18_H_tobu_for_unsupervise/val/normal/11'
  test:
    normal: '/dgx/shared/momo/inoue/somic/dataset/2020-06-18_H_tobu_for_unsupervise/test/normal/11'
    anomaly: '/dgx/shared/momo/inoue/somic/dataset/2020-06-18_H_tobu_for_unsupervise/test/anomaly/11'

augs:
  train:
  - name: 'ProbabilisticCrop'
    args:
      height: 128
      width: 128
      always_apply: True
      p: 1
  - name: 'Normalize'
    args:
      always_apply: True
      p: 1
  test:
  - name: 'Normalize'
    args:
      always_apply: True
      p: 1

optim:
  name: 'Adam'
  lr: 0.0002
  weight_decay: 0.00001

criterion:
  name: 'MSELoss'

pretrained_models:
  school:
  student:
  teacher:

train:
  epochs: 1000
  mini_epochs: 100
  batch_size: 1

test:
  batch_size: 64
  unfold_stride: 4