device: cuda:0
patch_size: 128

dataset:
  name: SomicDataset
  base: /dgx/shared/inoue/somic/dataset/H_ziku_unsupervise
  angle: 5
  train: ${dataset.base}/train/normal/${dataset.angle}
  val: ${dataset.base}/val/normal/${dataset.angle}
  test:
    normal: ${dataset.base}/test/normal/${dataset.angle}
    anomaly: ${dataset.base}/test/anomaly/${dataset.angle}

train:
  augs: /dgx/github/STAD/stad/yamls/train_augmentations.yaml
  pretrained:
    school:
    student:
    teacher:
  epochs: 4
  batch_size: 16
  optim:
    name: Adam
    lr: 0.0002
    weight_decay: 0.00001
  criterion:
    name: MSELoss

val:
  augs: /dgx/github/STAD/stad/yamls/test_augmentations.yaml
  data_num: 8

test:
  augs: /dgx/github/STAD/stad/yamls/test_augmentations.yaml
  batch_size: 32
  unfold_stride: 64
